title = "robwalt.dev"

base_url = "https://robwalt.dev"

compile_sass = true

theme = "hermit_zola"

build_search_index = true

taxonomies = [
           {name = "tags", rss = true}
]


[markdown]
highlight_code = true

[extra]
home_subtitle = "United we stand, devided we fall"

hermit_menu = [
    { link = "/voluntary", name = "Voluntary Work" },
    { link = "/books", name = "Books" },
    { link = "/posts", name = "Posts" },
    { link = "/about", name = "About" },
]

hermit_social = [
    { name = "mastodon", link = "https://mastodon.social/@RobWalt" },
    { name = "codeberg", link = "https://codeberg.org/RobWalt" },
    { name = "email", link = "mailto:robwalter96@gmail.com" },
    { name = "opencollective", link = "https://robwalt.dev/donations" }
]

[extra.author]
name = "Robert Walter"
homepage = "https://robwalt.gitlab.io/"
