title = "aviac.dev"

base_url = "https://aviac.dev"

compile_sass = true

theme = "hermit_zola"

build_search_index = true

taxonomies = [
  { name = "tags", rss = true }
]


[markdown]
highlight_code = true

[extra]
home_subtitle = "United we stand, divided we fall"

hermit_menu = [
    { link = "/voluntary", name = "Voluntary Work" },
    { link = "/dev-log", name = "Dev Logs" },
    # { link = "/donations", name = "Donations" },
]

hermit_social = [
    { name = "codeberg", link = "https://codeberg.org/Aviac" },
    { name = "email", link = "mailto:aviac@mailbox.org" },
    # { name = "opencollective", link = "https://aviac.dev/donations" },
    { name = "matrix", link = "@aviac:voidd.social" },
]

[extra.author]
name = "aviac"
homepage = "https://aviac.dev/"
